### ISSUE TITLE
build container g++13 for 1.7

### ISSUE THREAD

**Issue by lazan** [casualcore/casual#346]

**Comment by ahhud** [comment]
@lazan 
Fixed it for Suse. Some trouble for CentOS. 
CentOS as it used to be is deprecated. There is only a new variant called CentOS-stream not recommended in production. Internet users are quite mad. There is a new distro recommended. I think it was Rocky. And there are also UBI. So I chosed UBI8. 
And there is another problem. UBI8 is working but UBI9 is not because of lack of support of the chipset in the "wardrobe". It may be configurable by the wardrobe provider. 🙂
But problems are rising. 🙂
A separate problem is that devtoolset is now reworked and renamed under the name "gcc-toolset-13". That problem is manageable but requires changes in pipeline.
